---
# File: roles/hostmaster/tasks/main.yml
- name: create public key area
  file: path=/var/aegir/public_key state=directory
- name: copy public key to public key area
  copy: src=/var/aegir/.ssh/id_rsa.pub dest=/var/aegir/public_key/id_rsa.pub
- name: Create public key apache config
  copy: dest=/var/aegir/config/server_master/apache/pre.d/public_key.conf src=public_key.conf
